# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nice Food', max_length=128)),
                ('healthy_level', models.IntegerField(default=0)),
                ('taste_level', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
