# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='short_desc',
            field=models.CharField(default='Nice Food', max_length=512),
        ),
    ]
