# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicfood', '0002_food_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='Nice Food', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='short_desc',
            field=models.CharField(default='Nice Food', max_length=256),
        ),
    ]
