# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicfood', '0005_auto_20160918_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='healthy_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='taste_level',
            field=models.IntegerField(),
        ),
    ]
